site_name: Timo
theme:
  name: material
  palette:
    primary: white
    accent: deep orange
  icon:
    logo: fontawesome/solid/t
    # favicon: fontawesome/icons/t
    features:
      # - navigation.instant # some features may not work properly with XHR
      - navigation.tracking # the URL changes with the active anchor
      - navigation.tabs # first top-level sections are shown as tabs
      # - navigation.tabs.sticky # tabs always show
      # - navigation.sections # sections are rendered as groups in the sidebar
      # - navigation.expand # all sections are expanded
      - navigation.indexes # link an index.md page to a section
      - navigation.top # show back-to-top button
      # - toc.integrate # show table of contents to navigation panel
      # - header.autohide

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/tgaspar
      name: tgaspar
    - icon: fontawesome/brands/linkedin-in
      link: www.linkedin.com/in/timotej-gaspar
      name: Timotej Gašpar
generator: false # hide the line "Made with Material for MkDocs"
